#!/bin/bash
# a bash script to run every file in the test programs directory
# testPgms/correct/.
clear;
mut_types="-hb -s -e"
mode_types="-r -ct -v"

for mut_type in $mut_types
do
	for mode_type in $mode_types
	do
		for in_num in 5 6 7 8 9 10
		do
			echo python HereBoy.py 3 "$mut_type" "$mode_type" -i "$in_num"
		done
	done
done
